---
abstract: 'Process Geography Markup Language'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-GML
no_index:
  directory:
    - t
    - inc
requires:
  Geo::Point: 0.90
  Log::Report: 0.19
  Test::More: 0.54
  Test::Pod: 1.00
  XML::Compile: 1.28
  XML::Compile::Cache: 0.995
  XML::Compile::Tester: 0.04
version: 0.16
